export enum TypeOperation {
  RETRAITLIQUIDE = 'RETRAITLIQUIDE',

  DEPOTLIQUIDE = 'DEPOTLIQUIDE',

  VIREMENTINTERNE = 'VIREMENTINTERNE',

  VIREMENTEXTERNE = 'VIREMENTEXTERNE',

  PAIEMENTCHEQUE = 'PAIEMENTCHEQUE',

  PAIEMENTCB = 'PAIEMENTCB',

  DEPOTCHEQUE = 'DEPOTCHEQUE',
}
